version: '3.8'

services:
#  mysql:
#    hostname: ${DB_HOST}
#    image: mysql:latest
#    ports:
#      - "${DB_HOST_PORT:-3306}:3306"
#    environment:
#      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${APP_DB_NAME}
#      MYSQL_USER: ${APP_DB_USER}
#      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
#    volumes:
#      - beer-service-mysql-data:/var/lib/mysql
#      - ./docker/database/entrypoint:/docker-entrypoint-initdb.d
  jms:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - '8161:8161'
      - '61616:61616'
    environment:
      - ARTEMIS_USERNAME=artemis
      - ARTEMIS_PASSWORD=artemis
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
  eureka-server:
    image: egon89/mssc-brewery-eureka
    hostname: eureka-server-host
    ports:
      - '8761:8761'
  config-server:
    image: egon89/mssc-config-server
    ports:
      - '8888:8888'
    depends_on:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/ # we can use hostname too
      - eureka.instance.preferIpAddress=true
  inventory-service:
    image: egon89/mssc-beer-inventory-service
    ports:
      - '8082:8082'
    depends_on:
      - eureka-server
      - config-server
      - jms
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/ # we can use hostname too
      - eureka.instance.preferIpAddress=true
      - spring.profiles.active=local-discovery,localmysql
      - spring.zipkin.baseurl=http://zipkin
      - spring.artemis.broker-url=tcp://jms:61616
      - spring.artemis.user=artemis
      - spring.artemis.password=artemis
      - spring.datasource.username=beer_inventory
      - spring.datasource.password=secret
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/beer_inventory_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  beer-service-mysql-data:
