version: '3.8'

services:
  mysql:
    hostname: ${DB_HOST}
    image: mysql:latest
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - beer-service-mysql-data:/var/lib/mysql
      - ./docker/database/entrypoint:/docker-entrypoint-initdb.d

volumes:
  beer-service-mysql-data:
